apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-mysql-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.mysql.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.mysql.storageSize }}
