apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-wordpress-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.wordpress.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.wordpress.storageSize }}
