{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-kc-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: wordpress-service
      port:
        number: 80
  rules:
  - host: {{ .Values.configmap.WP_HOST }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
{{- end }}
      # - path: /apple
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: apple-service
      #       port:
      #         number: 5678
      # - path: /banana
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: banana-service
      #       port:
      #         number: 5678
      # - path: /pepe
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: wordpress-service
      #       port:
      #         number: 80
