{{- if .Values.service.loadBalancerEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-wordpress-loadbalancer
  namespace: {{ .Values.namespace }}
  # annotations:
    # kubernetes.digitalocean.com/load-balancer-id: "kc-lb-cluster"
    # service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
    # service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
{{- end }}